=== markitos1605/web2/mundogamer.dtd
<!-- DTD para el inventario juegos de la empresa -->
<!ELEMENT inventario (Juegos+)>
<!ELEMENT Juegos (empresa, usuario, nombre_tipo)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT nombre_tipo (#PCDATA)>
<!ATTLIST Juegos
    id ID #REQUIRED
>

=== markitos1605/web2/inventario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventario SYSTEM "mundogamer.dtd">
<inventario>
    <Juegos id="PC001">
        <empresa>Nintendo 5</empresa>
        <usuario>Marcos Feliz</usuario>
        <nombre_tipo>Inazuma Eleven</nombre_tipo>
    </ordenador>
    <ordenador id="PC002">
        <empresa>Nintendo 5</empresa>
        <usuario>Macaco</usuario>
        <nombre_tipo>Naruto</nombre_tipo>
    </ordenador>
</inventario>
